### ISSUE TITLE
MonoMod does it support for Debug mode? 

### ISSUE THREAD

**Issue by NRTnarathip** [Fireworkshh/SMAPI-New-Android#1]

**Comment by NRTnarathip** [comment]
i fork & editor MonoMod for android Debug mode but it not works for me
and MonoMod it's can't access protected field & method

**Comment by NRTnarathip** [comment]
Oh, wait did you use my Harmony.dll from my project?

**Comment by Fireworkshh** [comment]
No, this is Lemon Loader

**Comment by Fireworkshh** [comment]
另外一个是我自己编译的，这很简单

**Comment by Fireworkshh** [comment]
The other one is compiled by myself, which is very simple

**Comment by Fireworkshh** [comment]
I have two Harmonys and the other one doesn't work sometimes

**Comment by Fireworkshh** [comment]
I'm using both 0Harmony and the other one doesn't work sometimes

**Comment by Fireworkshh** [comment]
> 哦，等等，你用过我项目中的 Harmony.dll 了吗？

Sorry, the project is similar to yours. I'm looking for a way to repackage StardewValley in Xamarin, but I haven't found it yet. This is the only way for now.
